openapi: 3.0.0
info:
  title: Barcode Service API
  description: API Design for recognizing different barcode types on given image
  version: '1.0.0'
servers:
  - url: http://{{baseUrl}}/barcode/api/v1/
paths:
  /info:
    get:
      operationId: getInfo
      summary: Returns info about current name, version of the API
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InfoSchema'
  /recognize:
    post:
      operationId: recognize
      summary: Recognizes Barcodes of given types on given image. Is designed for use with different engine providers.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BarcodeRecognitionRequest'
            
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BarcodeRecognitionResponse'
components:
  schemas:
    InfoSchema:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
      required:
        - name
        - version
    BarcodeRecognitionRequest:
      type: object
      properties:
        engine:
          type: string
          enum:
            - qualitysoft
          default: qualitysoft
        source:
          $ref: '#/components/schemas/BarcodeSourceDto'
        barcodeTypes:
          type: array
          default: [any]
          items:
            $ref: '#/components/schemas/BarcodeTypeEnum'
        searchOrientation:
          type: string
          enum:
            - horizontal
            - vertical
            - horizontalVertical
            - horizontalVerticalDiagonal
          default: horizontalVertical
    BarcodeRecognitionResponse:
      type: object
      properties:
        barcodes:
          type: array
          items:
            type: object
            properties:
              barcodeValue: 
                type: string
              barcodeType:
                $ref: '#/components/schemas/BarcodeTypeEnum'
              barcodeArea:
                type: object
                description: Recognized Barcode Area (units in px)
                properties:
                  x:
                    type: number
                  y:
                    type: number
                  width:
                    type: number
                  height:
                    type: number
              barcodeCertainty:
                type: number
                format: int32
                minimum: -1
                maximum: 100
                description: Certainty between 0 and 100%. -1 indicates UNSUPPORTED
                
    BarcodeTypeEnum:
      type: string
      enum:
        - any
        - bcdMatrixBarcode
        - code128Barcode
        - code39Barcode
        - interleaved2Of5Barcode
        - pdf417Barcode
        - qrCodeBarcode
    BarcodeSourceDto:
      type: object
      description: Image to recognize barcodes on. Supported formats are [JPG,TIFF]
      minProperties: 1
      properties:
        image: 
          type: string
          format: byte
        imageURI:
          type: string
          format: uri